In [2]:
import numpy as np

In [3]:
ar=np.array([[10,20,30],[30,40,50]])
print(ar)

[[10 20 30]
 [30 40 50]]


In [4]:
sliced=ar[:1:,1:]
print(sliced)

[[20 30]]


In [5]:
indexed=ar[[0,1],[1,1]]
print(indexed)

[20 40]


In [6]:
#sum
print(ar.sum())


180


In [8]:
#sqrt
print(np.sqrt(ar))

[[3.16227766 4.47213595 5.47722558]
 [5.47722558 6.32455532 7.07106781]]


In [9]:
#add element in array
print(ar+10)

[[20 30 40]
 [40 50 60]]


In [11]:
m1=np.array([[1,2,3],[2,4,5],[1,2,4]])
m2=np.array([[2,4,3],[2,3,4],[12,3,4]])

m3=np.dot(m1,m2)
print(m3)

[[42 19 23]
 [72 35 42]
 [54 22 27]]


In [12]:
#transpose

print(m3.T)

[[42 72 54]
 [19 35 22]
 [23 42 27]]


In [13]:
bol=np.array([[True,True],[False,False]])
print(np.all(bol))

False


In [15]:
bol=np.array([[True,True],[True,True]])
print(np.all(bol))

True


In [17]:
bol=np.array([[True,True],[False,False]])
print(np.all(bol,axis=1))

[ True False]


In [19]:
bol=np.array([[True,True],[False,False]])
print(np.all(bol ,axis=0))

[False False]


In [22]:
bol=np.array([[True,True],[False,False]])
print(np.any(bol))

True


In [24]:
bol=np.array([[True,True],[False,False]])
print(np.all(bol,axis=1))

[ True False]


In [33]:
bol=np.array([[True,True],[False,False]])
print(np.any(bol,axis=1))

[ True False]


In [28]:
bol=np.array([[True,True],[False,False]])
print(np.any(bol,axis=0))

[ True  True]


In [34]:
#arrang
ar=np.arange(8)
print(ar)

[0 1 2 3 4 5 6 7]


In [36]:
#reshape

print(ar.reshape(2,4))

[[0 1 2 3]
 [4 5 6 7]]


In [38]:
#merge vstack
vstack=np.vstack((m1,m2,m3))
print(vstack)

[[ 1  2  3]
 [ 2  4  5]
 [ 1  2  4]
 [ 2  4  3]
 [ 2  3  4]
 [12  3  4]
 [42 19 23]
 [72 35 42]
 [54 22 27]]


In [40]:
#merge vstack
hstack=np.hstack((m1,m2,m3))
print(hstack)

[[ 1  2  3  2  4  3 42 19 23]
 [ 2  4  5  2  3  4 72 35 42]
 [ 1  2  4 12  3  4 54 22 27]]


In [43]:
#merge vstack
vspilt=np.vsplit(vstack,3)
print(vspilt)

[array([[1, 2, 3],
       [2, 4, 5],
       [1, 2, 4]]), array([[ 2,  4,  3],
       [ 2,  3,  4],
       [12,  3,  4]]), array([[42, 19, 23],
       [72, 35, 42],
       [54, 22, 27]])]


In [46]:
#merge vstack
vspilt=np.hsplit(vstack,3)
print(vspilt)

[array([[ 1],
       [ 2],
       [ 1],
       [ 2],
       [ 2],
       [12],
       [42],
       [72],
       [54]]), array([[ 2],
       [ 4],
       [ 2],
       [ 4],
       [ 3],
       [ 3],
       [19],
       [35],
       [22]]), array([[ 3],
       [ 5],
       [ 4],
       [ 3],
       [ 4],
       [ 4],
       [23],
       [42],
       [27]])]


In [48]:
#mathematical function

ar=np.array([2,3,4])
print('sqrt',np.sqrt(ar))
print('exp',np.exp(ar))
print('sin',np.sin(ar))
print('cos',np.cos(ar))
print('log',np.log(ar))
print('sum',np.sum(ar))
print('std',np.std(ar))

sqrt [1.41421356 1.73205081 2.        ]
exp [ 7.3890561  20.08553692 54.59815003]
sin [ 0.90929743  0.14112001 -0.7568025 ]
cos [-0.41614684 -0.9899925  -0.65364362]
log [0.69314718 1.09861229 1.38629436]
sum 9
std 0.816496580927726


In [50]:
#random

print(np.random.random(20))

[0.25307227 0.80361877 0.19629769 0.68291409 0.11676941 0.10048159
 0.32262335 0.09494979 0.68541417 0.20808645 0.46120245 0.76300922
 0.33411219 0.42517258 0.70139085 0.78587071 0.3195576  0.71824927
 0.83339088 0.28082042]


In [52]:
print(np.random.rand(3,4))

[[0.22909051 0.33731792 0.61215631 0.9445971 ]
 [0.93869652 0.97007567 0.01743006 0.02739277]
 [0.83621435 0.30782178 0.84020046 0.5556991 ]]


In [54]:
print(np.random.randint(0,100,20))

[75 56 35 50 18 59 66 21 89 88 54 21 38  0 23 51  5 80 72 33]


In [57]:
#permitution
print(np.random.permutation(np.arange(5)))

[1 0 4 2 3]
